### ISSUE TITLE
Pontos importantes, mas...

### ISSUE THREAD

**Issue by AlexandreDaltro** [lagolucas/resposta-urnas-2022#1]
Obrigado por levantar esses 2 pontos, que são muito importantes, mas a questão principal no meu ver é:
Houve diferença entre as votações, em cidades mais homogeneas (pequenas), onde a unica variante é a urna?
E se sim, por quê?

Essa pergunta só pode ser respondida com uma analise mais aprofundada...
Pelo que vi nesse relatório (https://t.co/eNpyF73FCR), feito em Python, existe um padrão de "Bolso foi melhor nas urnas 09 e 20, Lula foi melhor nas urnas 10", por região (Exceto no Sul).
(Mas por região é abrangente de mais, e não é possível chegar a conclusões de fato)

Pessoalmente não acreditava em fraude, mas o silêncio e as censuras do TSE só fazem crescer a desconfiança.

**Comment by lagolucas** [comment]
Esse ponto não é trazido no relatório. Por isso estava no item.

## Coisas que não vou responder nesse documento.
